# -*- coding: utf-8 -*-
"""ntlk.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lq8AQUQn9yAeOnHG_jdGL_kWClqurbi-
"""

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.sentiment.vader import SentimentIntensityAnalyzer
from wordcloud import WordCloud
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import LatentDirichletAllocation
from sklearn.cluster import KMeans
from collections import Counter
import nltk

# Download required NLTK data
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('stopwords')
nltk.download('vader_lexicon')

# -------------------------
# Streamlit page config
# -------------------------
st.set_page_config(page_title="Netflix NLP Dashboard", layout="wide")
st.title("📺 Netflix NLP Dashboard")

# -------------------------
# File uploader
# -------------------------
uploaded_file = st.file_uploader("Upload your Netflix CSV file", type=["csv"])
if uploaded_file is not None:
    df = pd.read_csv(uploaded_file)
    st.success(f"✅ Dataset loaded: {df.shape}")
    st.dataframe(df.head())

    # -------------------------
    # Combine title + description
    # -------------------------
    df['text'] = df['title'].fillna('') + " " + df['description'].fillna('')

    # -------------------------
    # Clean text
    # -------------------------
    def clean_text(text):
        text = str(text).lower()
        text = re.sub(r"http\S+|www.\S+", " ", text)
        text = re.sub(r"[^a-z\s]", " ", text)
        text = re.sub(r"\s+", " ", text).strip()
        return text

    df['clean_text'] = df['text'].apply(clean_text)

    # -------------------------
    # Tokenize + Lemmatize (no POS)
    # -------------------------
    stop_words = set(stopwords.words('english'))
    lemmatizer = WordNetLemmatizer()

    def preprocess(text):
        tokens = text.split()
        tokens = [t for t in tokens if t not in stop_words]
        tokens = [lemmatizer.lemmatize(t) for t in tokens]  # simple lemmatization
        return tokens

    df['tokens'] = df['clean_text'].apply(preprocess)

    # -------------------------
    # Sentiment Analysis
    # -------------------------
    sid = SentimentIntensityAnalyzer()
    df['vader_score'] = df['clean_text'].apply(lambda x: sid.polarity_scores(x)['compound'])
    df['sentiment'] = df['vader_score'].apply(
        lambda x: 'Positive' if x > 0.05 else ('Negative' if x < -0.05 else 'Neutral')
    )

    st.subheader("🎭 Sentiment Counts")
    st.bar_chart(df['sentiment'].value_counts())

    # -------------------------
    # WordCloud function
    # -------------------------
    def plot_wordcloud(text, title, colormap='viridis'):
        wordcloud = WordCloud(width=800, height=400, background_color='white', colormap=colormap).generate(text)
        plt.figure(figsize=(10,5))
        plt.imshow(wordcloud, interpolation='bilinear')
        plt.axis('off')
        plt.title(title)
        st.pyplot(plt)
        plt.close()

    # -------------------------
    # Barplot function for top words
    # -------------------------
    def plot_top_words(tokens_list, title, palette):
        words = [word for tokens in tokens_list for word in tokens]
        freq = Counter(words).most_common(20)
        if len(freq) == 0:
            st.write(f"No words to display for {title}")
            return
        words, counts = zip(*freq)
        plt.figure(figsize=(10,5))
        sns.barplot(x=counts, y=words, palette=palette)
        plt.title(title)
        st.pyplot(plt)
        plt.close()

    # -------------------------
    # Sentiment WordClouds & Top Words
    # -------------------------
    for sentiment, color in zip(['Positive', 'Negative', 'Neutral'], ['Greens', 'Reds', 'Blues']):
        st.subheader(f"WordCloud - {sentiment} Sentiment")
        text = " ".join(df[df['sentiment'] == sentiment]['clean_text'])
        plot_wordcloud(text, f"WordCloud of {sentiment} Netflix Titles & Descriptions", colormap=color)

        st.subheader(f"Top Words - {sentiment} Sentiment")
        plot_top_words(df[df['sentiment'] == sentiment]['tokens'], f"Top 20 Words in {sentiment} Descriptions", palette=color)

    # -------------------------
    # TF-IDF + LDA Topic Modeling
    # -------------------------
    tfidf = TfidfVectorizer(max_features=1000, stop_words='english', ngram_range=(1,2))
    X_tfidf = tfidf.fit_transform(df['clean_text'])

    lda = LatentDirichletAllocation(n_components=5, random_state=42)
    lda.fit(X_tfidf)
    feature_names = tfidf.get_feature_names_out()

    st.subheader("🧩 LDA Topic Modeling (Top 10 words per topic)")
    for i, topic in enumerate(lda.components_):
        st.write(f"**Topic {i+1}:**", [feature_names[j] for j in topic.argsort()[-10:]])

    # -------------------------
    # KMeans Clustering
    # -------------------------
    kmeans = KMeans(n_clusters=5, random_state=42)
    df['cluster'] = kmeans.fit_predict(X_tfidf)
    st.subheader("🎯 Cluster Counts")
    st.bar_chart(df['cluster'].value_counts())

    # -------------------------
    # Save processed CSV
    # -------------------------
    df.to_csv("netflix_nlp_streamlit.csv", index=False)
    st.success("✅ Enhanced NLP processing complete! Results saved to netflix_nlp_streamlit.csv")

!pip install streamlit