# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zOFZpqRVGZ-yojFKUkC7Thjd3vbffyMA
"""

import pandas as pd
import streamlit as st
import plotly.express as px
import os

st.set_page_config(page_title="Netflix Dashboard", layout="wide")
st.title("🎬 Netflix Titles Dashboard")

ACCENT = "#E50914"  # Netflix red

# Load dataset
possible_paths = [
    "./netflix_titles.csv",
    "../netflix_titles.csv",
    "netflix_titles.csv",
]

path = next((p for p in possible_paths if os.path.exists(p)), None)
if not path:
    st.error("❌ Could not find 'netflix_titles.csv'. Please upload the file.")
    st.stop()

df = pd.read_csv(path)

# Clean columns
df["release_year"] = pd.to_numeric(df["release_year"], errors="coerce").fillna(0).astype(int)
df["country"] = df["country"].fillna("Unknown")
df["type"] = df["type"].fillna("Unknown")

# Expand countries for filtering
df["country_list"] = df["country"].apply(lambda x: [c.strip() for c in str(x).split(",") if c.strip()])
df_expanded = df.explode("country_list")

# Sidebar Filters
st.sidebar.header("Filters")

type_select = st.sidebar.selectbox(
    "Type",
    ["All"] + sorted(df["type"].dropna().unique().tolist())
)

countries = sorted(df_expanded["country_list"].dropna().unique().tolist())
country_select = st.sidebar.multiselect(
    "Country",
    countries,
    default=["United States"] if "United States" in countries else []
)

year_range = st.sidebar.slider(
    "Release Year Range",
    int(df["release_year"].min()),
    int(df["release_year"].max()),
    (2000, 2020)
)

# Filter data
dff = df_expanded.copy()
if type_select != "All":
    dff = dff[dff["type"] == type_select]
if country_select:
    dff = dff[dff["country_list"].isin(country_select)]
dff = dff[
    (dff["release_year"] >= year_range[0]) &
    (dff["release_year"] <= year_range[1])
]
dff = dff.drop_duplicates(subset=["title"]).reset_index(drop=True)

# KPIs
st.header("📊 Key Metrics")
col1, col2, col3 = st.columns(3)
total = len(dff)
avg_year = int(dff["release_year"].mean()) if total > 0 else 0
top_country = dff["country_list"].mode().iloc[0] if total > 0 else "N/A"

col1.metric("Total Titles", f"{total:,}")
col2.metric("Average Release Year", avg_year)
col3.metric("Most Common Country", top_country)

st.divider()

# Plots
st.header("Overview")
chart_col1, chart_col2 = st.columns(2)

# Year plot
with chart_col1:
    if len(dff) > 0:
        df_year = dff.groupby("release_year").size().reset_index(name="Count")
        fig1 = px.bar(df_year, x="release_year", y="Count",
                      title="Titles by Release Year",
                      color_discrete_sequence=[ACCENT])
        st.plotly_chart(fig1, use_container_width=True)
    else:
        st.info("No data for selected filters.")

# Type plot
with chart_col2:
    if len(dff) > 0:
        counts = dff["type"].value_counts().reset_index()
        counts.columns = ["Type", "Count"]
        fig2 = px.bar(counts, x="Type", y="Count",
                      title="Content Type Distribution",
                      color_discrete_sequence=[ACCENT])
        st.plotly_chart(fig2, use_container_width=True)
    else:
        st.info("No data for selected filters.")

st.divider()

# Data Table
st.header("Data Table")
display_cols = ["title", "type", "country", "release_year", "rating", "duration"]
available_cols = [col for col in display_cols if col in dff.columns]
st.dataframe(dff[available_cols], use_container_width=True, height=400)

st.caption(f"Showing {len(dff)} titles")